### ISSUE TITLE
pod fails to start 

### ISSUE THREAD

**Issue by GodofGurus** [splunk/fluent-plugin-kubernetes-objects#4]
**error="Invalid Kubernetes API v1 endpoint https://10.0.0.1:443/api: SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)"**

2018-07-01 21:53:53 +0000 [info]: parsing config file is succeeded path="/fluentd/etc/fluent.conf"
2018-07-01 21:53:53 +0000 [warn]: both of Plugin @id and path for &lt;storage&gt; are not specified. Using on-memory store.
2018-07-01 21:53:53 +0000 [error]: config error file="/fluentd/etc/fluent.conf" error_class=Fluent::ConfigError error="Invalid Kubernetes API v1 endpoint https://10.0.0.1:443/api: SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)"
  2018-07-01 21:53:53 +0000 [debug]: /usr/local/bundle/gems/fluent-plugin-kubernetes-objects-1.0.0/lib/fluent/plugin/in_kubernetes_objects.rb:164:in `rescue in initialize_client'
  2018-07-01 21:53:53 +0000 [debug]: /usr/local/bundle/gems/fluent-plugin-kubernetes-objects-1.0.0/lib/fluent/plugin/in_kubernetes_objects.rb:161:in `initialize_client'
  2018-07-01 21:53:53 +0000 [debug]: /usr/local/bundle/gems/fluent-plugin-kubernetes-objects-1.0.0/lib/fluent/plugin/in_kubernetes_objects.rb:92:in `configure'
  2018-07-01 21:53:53 +0000 [debug]: /usr/local/bundle/gems/fluentd-1.2.0/lib/fluent/plugin.rb:164:in `configure'
  2018-07-01 21:53:53 +0000 [debug]: /usr/local/bundle/gems/fluentd-1.2.0/lib/fluent/root_agent.rb:282:in `add_source'
  2018-07-01 21:53:53 +0000 [debug]: /usr/local/bundle/gems/fluentd-1.2.0/lib/fluent/root_agent.rb:122:in `block in configure'
  2018-07-01 21:53:53 +0000 [debug]: /usr/local/bundle/gems/fluentd-1.2.0/lib/fluent/root_agent.rb:118:in `each'
  2018-07-01 21:53:53 +0000 [debug]: /usr/local/bundle/gems/fluentd-1.2.0/lib/fluent/root_agent.rb:118:in `configure'
  2018-07-01 21:53:53 +0000 [debug]: /usr/local/bundle/gems/fluentd-1.2.0/lib/fluent/engine.rb:131:in `configure'
  2018-07-01 21:53:53 +0000 [debug]: /usr/local/bundle/gems/fluentd-1.2.0/lib/fluent/engine.rb:96:in `run_configure'
  2018-07-01 21:53:53 +0000 [debug]: /usr/local/bundle/gems/fluentd-1.2.0/lib/fluent/supervisor.rb:795:in `run_configure'
  2018-07-01 21:53:53 +0000 [debug]: /usr/local/bundle/gems/fluentd-1.2.0/lib/fluent/supervisor.rb:579:in `dry_run'
  2018-07-01 21:53:53 +0000 [debug]: /usr/local/bundle/gems/fluentd-1.2.0/lib/fluent/supervisor.rb:597:in `supervise'
  2018-07-01 21:53:53 +0000 [debug]: /usr/local/bundle/gems/fluentd-1.2.0/lib/fluent/supervisor.rb:502:in `run_supervisor'
  2018-07-01 21:53:53 +0000 [debug]: /usr/local/bundle/gems/fluentd-1.2.0/lib/fluent/command/fluentd.rb:310:in `&lt;top (required)&gt;'
  2018-07-01 21:53:53 +0000 [debug]: /usr/local/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
  2018-07-01 21:53:53 +0000 [debug]: /usr/local/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
  2018-07-01 21:53:53 +0000 [debug]: /usr/local/bundle/gems/fluentd-1.2.0/bin/fluentd:8:in `&lt;top (required)&gt;'
  2018-07-01 21:53:53 +0000 [debug]: /usr/local/bundle/bin/fluentd:23:in `load'
  2018-07-01 21:53:53 +0000 [debug]: /usr/local/bundle/bin/fluentd:23:in `&lt;main&gt;'

**Comment by Gimi** [comment]
Hi @GodofGurus , according to your error message, it failed because it could not verify the certificate. In this case, you need to either set the `ca_file` or set `insecure_ssl` to `true`.

**Comment by Gimi** [comment]
Closing the issue due to it's been inactive for a month. Please let us know if you still have problem using the plugin.

**Comment by gp510** [comment]
I'm seeing this currently when deploying against EKS.

**Comment by gp510** [comment]
Revalidated that if ca_file is supplied in the YAML it works with `insecure_ssl` set to false.
