### ISSUE TITLE
No yum update possible in 1.1.8

### ISSUE THREAD

**Issue by ericrichtert** [splunk/fluent-plugin-kubernetes-objects#75]
We build our own image, based on this image, to do:
* yum update for the latest os updates
* set the uid of the fluent user to match out k8s env

Since version 1.1.8, the yum update in our image fails with:
`Step 3/5 : RUN groupmod -g 1000 fluent     && usermod -u 1000 fluent     && yum update -y     && chown -R fluent /fluentd && chgrp -R fluent /fluentd
 ---> Running in 3055ea01e16b
[91mTraceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/libdnf/error.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 658, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 571, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 922, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: libglib-2.0.so.0: cannot open shared object file: No such file or directory
`

This is caused by the rpm -e command itroduced in 1.1.8. Is it possible to undo this rpm command in the Dockerfile?

**Comment by rockb1017** [comment]
Hey, thanks for bringing reporting. 
for security reasons, it was required to remove those packages from image. 
I would say the only thing possible is to build the image locally (after removing `rpm -e` line from Dockerfile) and use that image as the base.

**Comment by harshit-splunk** [comment]
The issue is fixed since version 1.1.11
